services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/src/app:z
      - ./migrations:/src/migrations:z
      - /src/.venv
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - ./.env
    depends_on:
      - migration
      - postgres
    networks:
      - fast_network

  postgres:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_PORT: ${PG_PORT}
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $PG_SERVER -d $PG_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fast_network

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    # The command to execute the Alembic migration script
    command: ["uv", "run", "alembic", "upgrade", "head"]

    # This service should not restart after it has successfully completed its job
    restart: "no"
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fast_network

  seeder:
    build:
      context: .
      dockerfile: Dockerfile
    # The command to execute the Alembic migration script
    command: ["uv", "run", "-m", "app.seed.data"]

    # This service should not restart after it has successfully completed its job
    restart: "no"
    env_file:
      - ./.env
    depends_on:
      - migration
      - backend
    networks:
      - fast_network

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - fast_network

networks:
  fast_network:
    driver: bridge
